"use client";

import React from "react";
import { Field, FieldContent, FieldDescription, FieldGroup, FieldLabel, FieldSet, FieldTitle, } from "@/components/ui/field";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { sileo } from "sileo";
import { ArrowLeft, ArrowRight, CheckCircle2Icon } from "lucide-react";

interface Props {
    step: number;
    setStep: (step: number) => void;
    drNumber: string;
    setDrNumber: (v: string) => void;
    soNumber: string;
    setSoNumber: (v: string) => void;
    siAmount: string;
    setSiAmount: (v: string) => void;
    siDate: string;
    setSiDate: (v: string) => void;
    paymentTerms: string;
    setPaymentTerms: (v: string) => void;
    deliveryDate: string;
    setDeliveryDate: (v: string) => void;
    remarks: string;
    setRemarks: (v: string) => void;
    status: string;
    setStatus: (v: string) => void;
    handleBack: () => void;
    handleNext: () => void;
    handleSave: () => void;
}

const PAYMENT_TERMS = [
    { label: "COD", description: "Payment is collected upon delivery." },
    { label: "Check", description: "Payment through post-dated or current check." },
    { label: "Cash", description: "Cash payment upon confirmation or delivery." },
    { label: "Bank Deposit", description: "Payment via bank transfer or deposit." },
    { label: "GCash", description: "Payment via GCash wallet transfer." },
    { label: "Terms", description: "Credit terms apply (30/45/60 days)." },
];

export function DRSheet(props: Props) {
    const {
        step,
        drNumber,
        setDrNumber,
        soNumber,
        setSoNumber,
        siAmount,
        setSiAmount,
        siDate,
        setSiDate,
        paymentTerms,
        setPaymentTerms,
        deliveryDate,
        setDeliveryDate,
        remarks,
        setRemarks,
        status,
        setStatus,
        handleBack,
        handleNext,
        handleSave,
    } = props;

    /* ---------------- VALIDATIONS ---------------- */

    const isStep2Valid =
        drNumber.trim() !== "" &&
        siAmount.trim() !== "" &&
        !isNaN(Number(siAmount))

    const isStep3Valid =
        paymentTerms.trim() !== "" &&
        deliveryDate.trim() !== "";

    const isStep4Valid =
        remarks.trim() !== "" &&
        status === "Delivered";

    const handleNextStep2 = () => {
        if (!drNumber.trim())
            return
        if (!siAmount || isNaN(Number(siAmount)))
            return
        handleNext();
    };

    const handleNextStep3 = () => {
        if (!paymentTerms) return
        if (!deliveryDate) return
        handleNext();
    };

    /* ---------------- UI ---------------- */

    return (
        <>
            {/* STEP 2 — DR & SI */}
            {step === 2 && (
                <FieldGroup>
                    <FieldSet>
                        <FieldLabel className="font-bold">DR Number</FieldLabel>
                        <FieldDescription>Official Delivery Receipt reference.</FieldDescription>
                        <Input
                            className="uppercase rounded-none"
                            value={drNumber}
                            onChange={(e) => setDrNumber(e.target.value)}
                            placeholder="DR-000123"
                        />
                    </FieldSet>

                    {/* SO Number */}
                    <FieldSet>
                        <FieldLabel className="font-bold">SO Number</FieldLabel>
                        <p className="text-xs text-muted-foreground mb-1">
                            Enter the official Sales Order number issued by the client or generated by the accounting system (SAP).
                        </p>
                        <Input
                            type="text"
                            value={soNumber}
                            onChange={(e) => setSoNumber(e.target.value)}
                            placeholder="TF-SO-0000"
                            className="uppercase rounded-none"
                            required
                        />
                    </FieldSet>

                    <FieldSet>
                        <FieldLabel className="font-bold">Sales Invoice Amount</FieldLabel>
                        <FieldDescription>Total amount reflected on the Sales Invoice.</FieldDescription>
                        <Input
                            type="number"
                            min={0}
                            step="0.01"
                            value={siAmount}
                            onChange={(e) => setSiAmount(e.target.value)}
                            placeholder="0.00"
                            className="rounded-none"
                        />
                    </FieldSet>

                    <FieldSet className="mt-3">
                        <FieldLabel className="font-bold">Sales Invoice Date</FieldLabel>
                        <FieldDescription>Date the Sales Invoice was issued.</FieldDescription>
                        <Input
                            type="date"
                            value={siDate}
                            onChange={(e) => setSiDate(e.target.value)}
                            className="rounded-none"
                        />
                    </FieldSet>

                    <div className="flex justify-between mt-4">
                        <Button variant="outline" onClick={handleBack} className="rounded-none"><ArrowLeft /> Back</Button>
                        <Button onClick={handleNextStep2} disabled={!isStep2Valid} className="rounded-none">Next <ArrowRight /></Button>
                    </div>
                </FieldGroup>
            )}

            {/* STEP 3 — PAYMENT */}
            {step === 3 && (
                <FieldGroup>
                    <FieldSet className="mt-4">
                        <FieldLabel className="font-bold">Delivery Date</FieldLabel>
                        <FieldDescription>Actual date the items were delivered.</FieldDescription>
                        <Input
                            type="date"
                            value={deliveryDate}
                            onChange={(e) => setDeliveryDate(e.target.value)}
                            className="rounded-none"
                        />
                    </FieldSet>
                    <FieldSet>
                        <FieldLabel className="font-bold">Payment Terms</FieldLabel>

                        <RadioGroup value={paymentTerms} onValueChange={setPaymentTerms}>
                            {PAYMENT_TERMS.map(({ label, description }) => (
                                <FieldLabel key={label}>
                                    <Field orientation="horizontal" className="items-start">
                                        <FieldContent className="flex-1">
                                            <FieldTitle>{label}</FieldTitle>
                                            <FieldDescription>{description}</FieldDescription>

                                            {paymentTerms === label && (
                                                <div className="mt-4 flex gap-2">
                                                    <Button variant="outline" onClick={handleBack} className="rounded-none"><ArrowLeft /> Back</Button>
                                                    <Button onClick={handleNextStep3} disabled={!isStep3Valid} className="rounded-none">
                                                        Next <ArrowRight />
                                                    </Button>
                                                </div>
                                            )}
                                        </FieldContent>
                                        <RadioGroupItem value={label} />
                                    </Field>
                                </FieldLabel>
                            ))}
                        </RadioGroup>
                    </FieldSet>
                </FieldGroup>
            )}

            {/* STEP 4 — REMARKS & STATUS */}
            {step === 4 && (
                <FieldGroup>
                    <FieldSet>
                        <FieldLabel className="font-bold">Remarks</FieldLabel>
                        <FieldDescription>
                            Additional notes regarding delivery or payment.
                        </FieldDescription>
                        <Textarea
                            value={remarks}
                            onChange={(e) => setRemarks(e.target.value)}
                            placeholder="Enter remarks..."
                            className="rounded-none"
                        />
                    </FieldSet>

                    <FieldSet className="mt-6">
                        <FieldLabel className="font-bold">Status</FieldLabel>

                        <RadioGroup value={status} onValueChange={setStatus}>
                            <FieldLabel>
                                <Field orientation="horizontal" className="items-start">
                                    <FieldContent className="flex-1">
                                        <FieldTitle>Delivered</FieldTitle>
                                        <FieldDescription>
                                            Confirms that all required documents and delivery details are completed.
                                        </FieldDescription>

                                        {status === "Delivered" && (
                                            <div className="mt-4 flex gap-2">
                                                <Button variant="outline" onClick={handleBack} className="rounded-none"><ArrowLeft /> Back</Button>
                                                <Button onClick={handleSave} disabled={!isStep4Valid} className="rounded-none">
                                                    Save <ArrowRight />
                                                </Button>
                                            </div>
                                        )}
                                    </FieldContent>
                                    <RadioGroupItem value="Delivered" />
                                </Field>
                            </FieldLabel>
                        </RadioGroup>
                    </FieldSet>
                </FieldGroup>
            )}
        </>
    );
}
